/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATree: typeof import('ant-design-vue/es')['Tree']
    DaisyuiWrap: typeof import('./src/components/daisyui-wrap.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MenuItem: typeof import('./src/components/menu/menu-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
