/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATree: typeof import('ant-design-vue/es')['Tree']
    DaisuiWrap: typeof import('./src/components/daisui-wrap.vue')['default']
    DaisyuiWrap: typeof import('./src/components/daisyui-wrap.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MenuItem: typeof import('./src/components/menu/menu-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
